/* ============================================================
   PORTFOLIO — IVÁN ROJAS ROBLES
   Three.js (Neural Network) + GSAP + ScrollTrigger + Filters Engine
   ============================================================ */

// ── BASE DE DATOS DE PROYECTOS & CERTIFICACIONES ─────────────
const projects = [
  {
    id: "01",
    categories: ["hardware", "software"],
    primaryCategory: "hardware",
    typeLabel: "Robótica & IA",
    title: "Androide Bioinspirado Azra",
    desc: "Plataforma colaborativa para laboratorios de mecatrónica orientada a salvaguardar la integridad física, tutoría socrática y optimización de impresión 3D.",
    tags: ["Mecatrónica", "Visión IA", "Seguridad Activa", "Impresión 3D"],
    fullDesc: "El androide bioinspirado Azra opera como una plataforma colaborativa y de asistencia integral para laboratorios de mecatrónica. Está concebido para salvaguardar la integridad de los usuarios previniendo incidentes con gases tóxicos o conatos de incendio, brindar tutoría socrática a estudiantes y evitar el desperdicio masivo de insumos al identificar anomalías tempranas en procesos de impresión 3D.",
    file: "assets/Resumen_Infografia_Azra.pdf",
    fileLabel: "Ver Infografía Técnica",
    issuer: "Proyecto de Ingeniería Mecatrónica",
    isCert: false
  },
  {
    id: "02",
    categories: ["cert"],
    primaryCategory: "cert",
    typeLabel: "Certificación Oficial",
    title: "Diploma Siemens TIA Portal",
    desc: "Programación y Automatización Industrial con Controladores Lógicos Programables Siemens (TIA Portal) con 60 horas de formación técnica.",
    tags: ["Siemens", "TIA Portal", "PLC S7", "60 Horas STPS"],
    fullDesc: "Certificado de Reconocimiento otorgado por ABAG Engineering Solutions por haber acreditado satisfactoriamente el curso de formación técnica 'Programación y Automatización Industrial con PLC Siemens (TIA Portal)', con una duración total de 60 horas prácticas orientadas a arquitecturas industriales reales.",
    file: "assets/DIPLOMA SIEMENS - Rojas Robles Ivan.pdf",
    fileLabel: "Abrir Diploma Siemens (PDF)",
    issuer: "ABAG Engineering Solutions · 60 Horas",
    isCert: true,
    badgeText: "Acreditado 60 Horas"
  },
  {
    id: "03",
    categories: ["cert"],
    primaryCategory: "cert",
    typeLabel: "Certificación Oficial",
    title: "Constancia DC-3 STPS Siemens",
    desc: "Constancia oficial de competencias laborales de la Secretaría del Trabajo y Previsión Social (STPS) en PLCs Siemens avanzados.",
    tags: ["STPS México", "Formato DC-3", "Competencia Laboral", "PLC Siemens"],
    fullDesc: "Formato DC-3 expedido conforme a las directrices de la Secretaría del Trabajo y Previsión Social (STPS) de México. Acredita formalmente las competencias laborales de Iván Rojas Robles en 'Programación avanzada de Controladores Lógicos Programables SIEMENS' con una carga lectiva y práctica de 60 horas.",
    file: "assets/DC3 SIEMENS- Rojas Robles Ivan.pdf",
    fileLabel: "Abrir Constancia DC-3 STPS (PDF)",
    issuer: "STPS México · ABAG Engineering",
    isCert: true,
    badgeText: "Validez Oficial STPS"
  },
  {
    id: "04",
    categories: ["cert"],
    primaryCategory: "cert",
    typeLabel: "Certificación Oficial",
    title: "Semana de la Automatización",
    desc: "Entrenamiento especializado en programación de PLCs, instrumentación y simulación 3D de líneas de producción por Control+.",
    tags: ["Control+", "Automatización", "Simulación 3D", "Lazo Cerrado"],
    fullDesc: "Certificado de Participación y Aprobación en la 'Semana de la Automatización Industrial' validado por el centro de capacitación técnica Control+. El programa cubrió simulación avanzada de entornos de manufactura en 3D sin dependencia de hardware físico e instrumentación con PLC para control de variables analógicas de proceso.",
    file: "assets/Ivan Rojas Robles.pdf",
    fileLabel: "Abrir Certificado Control+ (PDF)",
    issuer: "Control+ Automatización Industrial",
    isCert: true,
    badgeText: "Simulación & Control"
  },
  {
    id: "05",
    categories: ["cert", "software"],
    primaryCategory: "cert",
    typeLabel: "Certificación Oficial",
    title: "Masterclass 4.0 | IngeLearn",
    desc: "Capacitación intensiva en Python para entornos industriales, Inteligencia Artificial aplicada y Ciberseguridad OT/IT.",
    tags: ["Industria 4.0", "Python", "IA Aplicada", "Ciberseguridad"],
    fullDesc: "Certificado de Participación emitido por la institución IngeLearn tras completar con éxito la capacitación 'Masterclass 4.0: Python, Inteligencia Artificial y Ciberseguridad aplicados a la Industria'. Especialización enfocada en la digitalización, análisis de datos y protección en plantas automatizadas.",
    file: "assets/Ivan-Rojas-3-6865D22A130B9-2025-07-02-21-43-22.pdf",
    fileLabel: "Abrir Certificado IngeLearn (PDF)",
    issuer: "IngeLearn · Industria 4.0",
    isCert: true,
    badgeText: "Especialización 4.0"
  },
  {
    id: "06",
    categories: ["hardware", "software"],
    primaryCategory: "hardware",
    typeLabel: "IoT / Salud Biomédica",
    title: "Pulsera de Monitoreo Cardíaco",
    desc: "Dispositivo wearable con ESP32, sensor MAX30102, acelerómetro MPU-6050 y transmisión telemática en tiempo real a Firebase.",
    tags: ["ESP32", "MAX30102", "MPU-6050", "Firebase", "Salud IoT"],
    fullDesc: "Diseño e implementación de un prototipo portátil en forma de pulsera para el monitoreo continuo de signos vitales (frecuencia cardíaca y pulsioximetría SpO2). Integra microcontrolador ESP32, sensor óptico MAX30102 y un acelerómetro/giroscopio MPU-6050 para detección automática de caídas, enlazado vía WiFi con Firebase y una app móvil de alerta médica.",
    file: "assets/Desarrollo de un prototipo portátil de monitoreo cardiaco en forma de pulsera.pdf",
    fileLabel: "Leer Documento Técnico",
    issuer: "Desarrollo Biomédico & IoT",
    isCert: false
  },
  {
    id: "07",
    categories: ["hardware", "software"],
    primaryCategory: "hardware",
    typeLabel: "IA & Seguridad Activa",
    title: "Casco Inteligente para Motociclistas",
    desc: "Sistema embebido de seguridad predictiva con ESP32, sensores IMU, módulo GPS y análisis en tiempo real para detección de colisiones.",
    tags: ["IA", "ESP32", "Sensores IMU", "GPS", "Seguridad Activa"],
    fullDesc: "Casco inteligente con Inteligencia Artificial diseñado como sistema de protección activa. Monitorea mediante sensores inerciales de alta frecuencia y geolocalización GPS las dinámicas del vehículo, detectando impactos severos o derrapes para disparar protocolos de emergencia y transmisión de coordenadas a servicios de asistencia.",
    file: "assets/El Casco Inteligente con IA es un sistema de seguridad activa diseñado para motociclistas, capaz de detectar accidentes en tiempo real mediante la combina.pdf",
    fileLabel: "Leer Ensayo & Arquitectura",
    issuer: "Sistemas Embebidos Inteligentes",
    isCert: false
  },
  {
    id: "08",
    categories: ["hardware"],
    primaryCategory: "hardware",
    typeLabel: "Robótica Aplicada",
    title: "Brazo Robótico Articulado",
    desc: "Diseño cinemático en SolidWorks, manufactura digital por corte láser en MDF y control servomotorizado con Arduino Uno.",
    tags: ["SolidWorks", "Corte Láser", "Arduino Uno", "Servomotores"],
    fullDesc: "Diseño, fabricación y puesta en marcha de un brazo robótico articulado multi-eje. El desarrollo abarcó el modelado 3D de piezas en SolidWorks, corte y ensamblaje de precisión en MDF, cableado de servomotores y programación en C++ para Arduino para manipulación manual por potenciómetros.",
    file: "assets/Brazo Robotico.pdf",
    fileLabel: "Descargar Reporte Técnico",
    issuer: "Ingeniería Mecatrónica",
    isCert: false
  },
  {
    id: "09",
    categories: ["hardware"],
    primaryCategory: "hardware",
    typeLabel: "Agrotech & Automatización",
    title: "Agronauta Verde",
    desc: "Invernadero automatizado autosustentable con paneles solares fotovoltaicos, telemetría Bluetooth/WiFi y monitoreo edáfico.",
    tags: ["ESP32", "Energía Solar", "Sensores de Suelo", "WiFi / BLE"],
    fullDesc: "Solución de agrotecnología sustentable impulsada mediante energía solar fotovoltaica. Optimiza el cuidado agronómico supervisando humedad, temperatura y conductividad iónica del suelo a distancia vía conectividad inalámbrica, automatizando electroválvulas y ventiladores sin intervención humana continua.",
    file: "assets/Agronauta Verde Tríptico.pdf",
    fileLabel: "Ver Tríptico del Proyecto",
    issuer: "Automatización Sustentable",
    isCert: false
  },
  {
    id: "10",
    categories: ["software", "hardware"],
    primaryCategory: "software",
    typeLabel: "Manufactura Digital & CAD",
    title: "Diseño, CAD & Fabricación Digital",
    desc: "Modelado paramétrico avanzado en SolidWorks y Fusion 360, maquinado en Router CNC, manufactura aditiva e inyección.",
    tags: ["SolidWorks", "Fusion 360", "Router CNC", "Impresión 3D"],
    fullDesc: "Documentación y ejecución práctica de metodologías de ingeniería inversa y prototipado rápido con SolidWorks y Fusion 360. Implementación de manufactura digital que incluye mecanizado en router CNC para acrílico y maderas, optimización FDM en impresión 3D, corte láser y concepción de moldes.",
    file: "assets/Proyecto de ingenieria.pdf",
    fileLabel: "Ver Portafolio de Fabricación",
    issuer: "Manufactura & CAD Avanzado",
    isCert: false
  },
  {
    id: "11",
    categories: ["invest"],
    primaryCategory: "invest",
    typeLabel: "Investigación & Sociedad",
    title: "The Trueque of Cholula",
    desc: "Estudio sobre la permanencia sociocultural y económica del trueque prehispánico tradicional en San